name: Docker publish

on:
  workflow_dispatch:
  push:
    branches:
      - main

env:
  IMAGE_NAME: shellcheck

jobs:
  build_push:
    environment: production
    runs-on: ubuntu-latest
    name: Build and push

    steps:
      - uses: actions/checkout@v4
      - name: Build image
        run: docker build --file Dockerfile --tag $IMAGE_NAME .
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push image
        run: |
          GH_IMAGE_ID=ghcr.io/${{ github.repository }}/$IMAGE_NAME
          DH_IMAGE_ID=andreccosta/$IMAGE_NAME

          docker tag $IMAGE_NAME $GH_IMAGE_ID:latest
          docker tag $IMAGE_NAME $DH_IMAGE_ID:latest
          docker push $GH_IMAGE_ID:latest
          docker push $DH_IMAGE_ID:latest
